# Configuración simple para DQN
seed: 42
learning_rate: 2.5e-4
buffer_size: 100000
batch_size: 64
gamma: 0.99
train_freq: 4
target_update_interval: 1000
exploration_fraction: 0.3
exploration_final_eps: 0.05
total_timesteps: 200000
patch_h: 13
patch_w: 13
canales: 8  # 0..5 (pavimento, muro, afueras, aceite, terracería, boost)